# -*- coding: utf-8 -*-
"""Go_bricks_2.1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fbXqgaaoRBbqJ9QUxwe6culkoRgkn_Oo
"""

# Step 1: Dataset download karo — run karo ye pehle
!pip install openmeteo-requests requests-cache retry-requests pandas numpy

import openmeteo_requests
import requests_cache
import pandas as pd
import numpy as np
from retry_requests import retry

# ─── OPEN-METEO SE DATA FETCH ─────────────────────────
cache_session = requests_cache.CachedSession('.cache', expire_after=-1)
retry_session = retry(cache_session, retries=5, backoff_factor=0.2)
openmeteo = openmeteo_requests.Client(session=retry_session)

# Tumhari factory ka location daalo (yahan Mumbai use kiya)
params = {
    "latitude": 19.07,       # ← apna city ka lat/long daalo
    "longitude": 72.87,
    "start_date": "2010-01-01",
    "end_date": "2024-12-31",  # 15 saal ka data
    "hourly": [
        "temperature_2m",
        "relative_humidity_2m",
        "wind_speed_10m",
        "wind_direction_10m",
        "cloud_cover",
        "precipitation",
        "surface_pressure",
        "shortwave_radiation"   # Solar irradiance — solar prediction ke liye
    ]
}

responses = openmeteo.weather_api(
    "https://archive-api.open-meteo.com/v1/archive", params=params
)
response = responses[0]
hourly = response.Hourly()

# DataFrame banao
df = pd.DataFrame({
    "timestamp":    pd.date_range(
                        start=pd.to_datetime(hourly.Time(), unit="s"),
                        periods=hourly.Variables(0).ValuesAsNumpy().shape[0],
                        freq="h"),
    "temperature":  hourly.Variables(0).ValuesAsNumpy(),
    "humidity":     hourly.Variables(1).ValuesAsNumpy(),
    "wind_speed":   hourly.Variables(2).ValuesAsNumpy(),
    "wind_dir":     hourly.Variables(3).ValuesAsNumpy(),
    "cloud_cover":  hourly.Variables(4).ValuesAsNumpy(),
    "precipitation":hourly.Variables(5).ValuesAsNumpy(),
    "pressure":     hourly.Variables(6).ValuesAsNumpy(),
    "solar_rad":    hourly.Variables(7).ValuesAsNumpy(),
})

df.to_csv("weather_data.csv", index=False)
print(f"Dataset ready! Shape: {df.shape}")
print(df.head())

df.tail()

import matplotlib.pyplot as plt

plt.figure(figsize=(12, 6))
plt.plot(df['timestamp'], df['precipitation'])
plt.title('Precipitation Over Time')
plt.xlabel('Date')
plt.ylabel('Precipitation')
plt.grid(True)
plt.show()

df['precipitation']

statistics = df['precipitation'].describe()
print(statistics)

import pandas as pd
import numpy as np

df = pd.read_csv("weather_data.csv")

# ─── LABEL 1: Storm coming? (0 = No, 1 = Yes) ──────────
# Storm = high wind + high cloud + rain combination
df["storm_score"] = (
    (df["wind_speed"] > 25).astype(int) * 2 +    # Strong wind
    (df["cloud_cover"] > 80).astype(int) +         # Heavy clouds
    (df["precipitation"] > 2).astype(int) +        # Rain
    (df["pressure"] < 1005).astype(int)            # Low pressure = storm
)
df["storm_label"] = (df["storm_score"] >= 3).astype(int)

# ─── LABEL 2: Solar drop % predict karo ─────────────────
# Normal solar max = 800 W/m² assume karo
NORMAL_SOLAR = df["solar_rad"].quantile(0.90)  # Clear day value
df["solar_drop_pct"] = np.clip(
    1 - (df["solar_rad"] / (NORMAL_SOLAR + 1e-6)), 0, 1
) * 100  # 0% to 100%

# ─── LABEL 3: Wind drop % predict karo ──────────────────
# Wind turbines rated speed = 12 m/s, shutdown > 25 m/s
RATED_WIND = 12.0
df["wind_power"] = np.clip(df["wind_speed"] / RATED_WIND, 0, 1)
NORMAL_WIND = df["wind_power"].quantile(0.90)
df["wind_drop_pct"] = np.clip(
    1 - (df["wind_power"] / (NORMAL_WIND + 1e-6)), 0, 1
) * 100

# Check karo
print("Storm events in dataset:", df["storm_label"].sum())
print("Avg solar drop on storm days:",
      df[df["storm_label"]==1]["solar_drop_pct"].mean().round(1), "%")
print("Avg wind drop on storm days:",
      df[df["storm_label"]==1]["wind_drop_pct"].mean().round(1), "%")

df.to_csv("weather_labeled.csv", index=False)

df.shape

import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
import tensorflow as tf
from tensorflow.keras.models import Sequential, Model # Added Model
from tensorflow.keras.layers import LSTM, Dense, Dropout, Input, RepeatVector, TimeDistributed # Added Input, RepeatVector, TimeDistributed
import matplotlib.pyplot as plt
import joblib

# ─── DATA LOAD ───────────────────────────────────────────
df = pd.read_csv("weather_labeled.csv").dropna()

FEATURES = ["temperature", "humidity", "wind_speed",
            "cloud_cover", "precipitation", "pressure", "solar_rad"]

TARGETS = ["storm_label", "solar_drop_pct", "wind_drop_pct"]

# ─── SCALING ─────────────────────────────────────────────
scaler_X = MinMaxScaler()
scaler_y = MinMaxScaler()

X_scaled = scaler_X.fit_transform(df[FEATURES])
y_scaled = scaler_y.fit_transform(df[TARGETS])

# ─── SEQUENCE BANANA (LSTM ke liye zaroori) ─────────
SEQ_LEN      = 24   # same as before — 24h input history
PRED_HORIZON = 6    # NEW — predict next 6 hours

def make_multistep_sequences(X, y, seq_len, horizon):
    Xs, ys = [], []
    for i in range(len(X) - seq_len - horizon + 1):
        Xs.append(X[i : i + seq_len])
        ys.append(y[i + seq_len : i + seq_len + horizon])
    return np.array(Xs), np.array(ys)

X_seq, y_seq = make_multistep_sequences(X_scaled, y_scaled, SEQ_LEN, PRED_HORIZON)
print(f"X shape: {X_seq.shape}  →  (samples, {SEQ_LEN}h input, {len(FEATURES)} features)")
print(f"y shape: {y_seq.shape}  →  (samples, {PRED_HORIZON}h forecast, {len(TARGETS)} targets)")

# ─── TRAIN/TEST SPLIT (time order — no shuffle) ──────────
split        = int(len(X_seq) * 0.80)
X_train, X_test = X_seq[:split], X_seq[split:]
y_train, y_test = y_seq[:split], y_seq[split:]
print(f"Train: {X_train.shape[0]} samples  |  Test: {X_test.shape[0]} samples")

#  NEW architecture (multi-step):
#    ENCODER: LSTM(128) → LSTM(64)  → context vector
#    BRIDGE:  RepeatVector(6)        → repeat for each forecast hour
#    DECODER: LSTM(64) → LSTM(32)   → TimeDistributed Dense
#    Output shape: (batch, 6, 3)    ← next 6 hours × 3 targets
# ════════════════════════════════════════════════════════════
inp     = Input(shape=(SEQ_LEN, len(FEATURES)), name="encoder_input")

# Encoder — reads 24h history and compresses to context vector
enc1    = LSTM(128, return_sequences=True,  name="encoder_lstm1")(inp)
enc1    = Dropout(0.2)(enc1)
enc_out = LSTM(64,  return_sequences=False, name="encoder_lstm2")(enc1)
enc_out = Dropout(0.2)(enc_out)

# Bridge — copy context vector once per forecast step
repeated = RepeatVector(PRED_HORIZON, name="repeat_context")(enc_out)

# Decoder — unrolls over 6 future hours
dec1    = LSTM(64, return_sequences=True, name="decoder_lstm1")(repeated)
dec1    = Dropout(0.2)(dec1)
dec2    = LSTM(32, return_sequences=True, name="decoder_lstm2")(dec1)

# Output — 3 target values per hour, for 6 hours
out     = TimeDistributed(Dense(16, activation="relu"),            name="td_hidden")(dec2)
out     = TimeDistributed(Dense(len(TARGETS), activation="sigmoid"), name="td_output")(out)
# Final shape: (batch, 6, 3)

model = Model(inputs=inp, outputs=out, name="MultiStep_EncoderDecoder_LSTM")
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    loss="mse",
    metrics=["mae"]
)
model.summary()

# ─── TRAINING ────────────────────────────────────────────
history = model.fit(
    X_train, y_train,
    epochs=30,
    batch_size=64,
    validation_split=0.1,
    callbacks=[
        tf.keras.callbacks.EarlyStopping(
            patience=7, restore_best_weights=True, monitor="val_loss"
        ),
        tf.keras.callbacks.ReduceLROnPlateau(
            factor=0.5, patience=3, min_lr=1e-5, verbose=1
        )
    ],
    verbose=1
)

import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, accuracy_score
import tensorflow as tf
from tensorflow.keras.models import Sequential, Model # Added Model
from tensorflow.keras.layers import LSTM, Dense, Dropout, Input, RepeatVector, TimeDistributed # Added Input, RepeatVector, TimeDistributed
import matplotlib.pyplot as plt
import joblib

#  NEW: y_pred shape (samples, 6, 3) → flatten → inverse → per-hour metrics
# ════════════════════════════════════════════════════════════
y_pred_sc  = model.predict(X_test, verbose=0)           # (samples, 6, 3)

y_pred_inv = scaler_y.inverse_transform(
                 y_pred_sc.reshape(-1, len(TARGETS)))    # flatten → unscale
y_true_inv = scaler_y.inverse_transform(
                 y_test.reshape(-1, len(TARGETS)))

print("\n=== OVERALL TEST RESULTS ===")
for i, name in enumerate(["Storm (0/1)", "Solar drop %", "Wind drop %"]):
    mae  = mean_absolute_error(y_true_inv[:, i], y_pred_inv[:, i])
    rmse = np.sqrt(mean_squared_error(y_true_inv[:, i], y_pred_inv[:, i]))
    print(f"  {name:<18}: MAE={mae:.3f}  RMSE={rmse:.3f}")

print("\n=== PER-HOUR ACCURACY (next 6 hours) ===")
for h in range(PRED_HORIZON):
    yp  = scaler_y.inverse_transform(y_pred_sc[:, h, :])
    yt  = scaler_y.inverse_transform(y_test[:,  h, :])
    acc = accuracy_score((yt[:, 0] > 0.5).astype(int),
                         (yp[:, 0] > 0.5).astype(int))
    s_mae = mean_absolute_error(yt[:, 1], yp[:, 1])
    w_mae = mean_absolute_error(yt[:, 2], yp[:, 2])
    print(f"  +{h+1}h | Storm acc: {acc*100:.1f}%  "
          f"Solar MAE: {s_mae:.1f}%  Wind MAE: {w_mae:.1f}%")

# ─── SAVE ────────────────────────────────────────────────
model.save("weather_multistep_model.keras")   # modern format (.keras not .h5)
joblib.dump(scaler_X, "scaler_X.pkl")
joblib.dump(scaler_y, "scaler_y.pkl")
print("\nModel saved → weather_multistep_model.keras")

# ─── TRAINING CURVE PLOT ─────────────────────────────────
plt.figure(figsize=(10, 4))
plt.subplot(1, 2, 1)
plt.plot(history.history["loss"],     label="Train Loss")
plt.plot(history.history["val_loss"], label="Val Loss")
plt.title("Training Loss"); plt.legend(); plt.grid(True, alpha=0.3)

plt.subplot(1, 2, 2)
plt.plot(history.history["mae"],     label="Train MAE")
plt.plot(history.history["val_mae"], label="Val MAE")
plt.title("Training MAE"); plt.legend(); plt.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig("training_curve.png", dpi=150)
plt.show()
print("training_curve.png saved!")

# ════════════════════════════════════════════════════════════
#  NEW: Prediction function — use this in real-time server
#
#  Input : last 24h weather DataFrame  (columns = FEATURES)
#  Output: per-hour forecast for next 6 hours + storm ETA
# ════════════════════════════════════════════════════════════
def predict_next_6_hours(last_24h_df, normal_green_mw=150.0):
    SOLAR_SHARE = 0.55
    WIND_SHARE  = 0.45

    X   = scaler_X.transform(last_24h_df[FEATURES])   # scale
    X   = X.reshape(1, SEQ_LEN, len(FEATURES))         # add batch dim
    raw = model.predict(X, verbose=0)[0]               # (6, 3) scaled
    inv = scaler_y.inverse_transform(raw)              # (6, 3) original units

    rows, storm_eta = [], None
    print("\n" + "=" * 60)
    print("  MULTI-STEP FORECAST — Next 6 Hours")
    print("=" * 60)
    print(f"  {'Hour':<6} {'Storm%':<10} {'Solar drop':<14} "
          f"{'Wind drop':<12} {'Deficit MW'}")
    print("  " + "-" * 58)

    for h in range(PRED_HORIZON):
        sp      = float(np.clip(inv[h, 0], 0, 1))
        sd      = float(np.clip(inv[h, 1], 0, 100))
        wd      = float(np.clip(inv[h, 2], 0, 100))
        deficit = round(
            normal_green_mw * SOLAR_SHARE * (sd / 100) +
            normal_green_mw * WIND_SHARE  * (wd / 100), 1
        )
        is_storm = sp >= 0.60
        if is_storm and storm_eta is None:
            storm_eta = h + 1
        bar = "█" * int(sp * 15) + "░" * (15 - int(sp * 15))
        tag = "  ← STORM!" if is_storm else ""
        print(f"  +{h+1}h   [{bar}] {sp*100:>4.0f}%   "
              f"{sd:>5.1f}%         {wd:>5.1f}%    {deficit:>6.1f} MW{tag}")
        rows.append(dict(hour=h+1, storm_prob=round(sp*100,1),
                         solar_drop_pct=round(sd,1),
                         wind_drop_pct=round(wd,1),
                         deficit_mw=deficit, is_storm=is_storm))

    print("=" * 60)
    if storm_eta:
        print(f"\n  ALERT  : Storm in +{storm_eta}h  ({storm_eta*60} minutes)")
        print(f"  Window : {storm_eta*60 - 15} min before impact — act now!")
    else:
        print("\n  OK — No storm expected in next 6 hours")

    return pd.DataFrame(rows), storm_eta


# ─── QUICK TEST ──────────────────────────────────────────
sample_df        = df[FEATURES].iloc[-24:].reset_index(drop=True)
forecast_df, eta = predict_next_6_hours(sample_df)
print("\nForecast DataFrame:")
print(forecast_df.to_string(index=False))

import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import (mean_absolute_error,
                             mean_squared_error,
                             accuracy_score,
                             f1_score)
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

# ─── LOAD DATA ───────────────────────────────────────────
df = pd.read_csv("weather_labeled.csv").dropna().reset_index(drop=True)

FEATURES = ["temperature", "humidity", "wind_speed",
            "cloud_cover", "precipitation", "pressure", "solar_rad"]
TARGETS  = ["storm_label", "solar_drop_pct", "wind_drop_pct"]

SEQ_LEN  = 24   # 24 ghante ka history
N_SPLITS = 5    # 5 folds

# ─── SEQUENCE BUILDER ────────────────────────────────────
def make_sequences(X, y, seq_len):
    Xs, ys = [], []
    for i in range(len(X) - seq_len):
        Xs.append(X[i:i+seq_len])
        ys.append(y[i+seq_len])
    return np.array(Xs), np.array(ys)

# ─── MODEL BUILDER ───────────────────────────────────────
def build_model(seq_len, n_features, n_targets):
    model = Sequential([
        LSTM(64, return_sequences=True,
             input_shape=(seq_len, n_features)),
        Dropout(0.2),
        LSTM(32, return_sequences=False),
        Dropout(0.2),
        Dense(16, activation='relu'),
        Dense(n_targets, activation='sigmoid')
    ])
    model.compile(optimizer='adam', loss='mse', metrics=['mae'])
    return model

# ─── WALK-FORWARD CV ─────────────────────────────────────
print("=" * 55)
print("   WALK-FORWARD CROSS VALIDATION — WEATHER LSTM")
print("=" * 55)

# Results store karne ke liye
fold_results = []

# Data ko N_SPLITS + 1 equal parts mein baanto
total_len  = len(df)
fold_size  = total_len // (N_SPLITS + 1)

for fold in range(N_SPLITS):
    print(f"\n--- Fold {fold+1}/{N_SPLITS} ---")

    # Train = sab pehle ka data
    train_end  = fold_size * (fold + 1)
    test_start = train_end
    test_end   = test_start + fold_size

    df_train = df.iloc[:train_end]
    df_test  = df.iloc[test_start:test_end]

    print(f"  Train size: {len(df_train)} rows "
          f"({df_train['timestamp'].iloc[0][:10]} → "
          f"{df_train['timestamp'].iloc[-1][:10]})")
    print(f"  Test size : {len(df_test)} rows "
          f"({df_test['timestamp'].iloc[0][:10]} → "
          f"{df_test['timestamp'].iloc[-1][:10]})")

    # Har fold mein fresh scaler fit karo (data leakage avoid)
    scaler_X = MinMaxScaler()
    scaler_y = MinMaxScaler()

    X_train_sc = scaler_X.fit_transform(df_train[FEATURES])
    y_train_sc = scaler_y.fit_transform(df_train[TARGETS])

    # Test pe sirf transform — fit nahi (important!)
    X_test_sc  = scaler_X.transform(df_test[FEATURES])
    y_test_sc  = scaler_y.transform(df_test[TARGETS])

    # Sequences banao
    X_tr, y_tr = make_sequences(X_train_sc, y_train_sc, SEQ_LEN)
    X_te, y_te = make_sequences(X_test_sc,  y_test_sc,  SEQ_LEN)

    if len(X_tr) < 100 or len(X_te) < 10:
        print("  Fold too small, skipping...")
        continue

    # Model train karo
    model = build_model(SEQ_LEN, len(FEATURES), len(TARGETS))
    model.fit(
        X_tr, y_tr,
        epochs=20,
        batch_size=32,
        validation_split=0.1,
        callbacks=[EarlyStopping(patience=3,
                                 restore_best_weights=True)],
        verbose=0   # Silent training
    )

    # Predict karo
    y_pred_sc = model.predict(X_te, verbose=0)

    # Inverse transform — original scale pe laao
    y_pred = scaler_y.inverse_transform(y_pred_sc)
    y_true = scaler_y.inverse_transform(y_te)

    # ─── METRICS ─────────────────────────────────────────
    # Storm detection (classification metrics)
    storm_true = (y_true[:, 0] > 0.5).astype(int)
    storm_pred = (y_pred[:, 0] > 0.5).astype(int)
    storm_acc  = accuracy_score(storm_true, storm_pred)
    storm_f1   = f1_score(storm_true, storm_pred, zero_division=0)

    # Solar drop (regression metrics)
    solar_mae  = mean_absolute_error(y_true[:, 1], y_pred[:, 1])
    solar_rmse = np.sqrt(mean_squared_error(y_true[:, 1], y_pred[:, 1]))

    # Wind drop (regression metrics)
    wind_mae   = mean_absolute_error(y_true[:, 2], y_pred[:, 2])
    wind_rmse  = np.sqrt(mean_squared_error(y_true[:, 2], y_pred[:, 2]))

    result = {
        "fold"       : fold + 1,
        "storm_acc"  : round(storm_acc  * 100, 1),
        "storm_f1"   : round(storm_f1,          3),
        "solar_mae"  : round(solar_mae,          2),
        "solar_rmse" : round(solar_rmse,         2),
        "wind_mae"   : round(wind_mae,           2),
        "wind_rmse"  : round(wind_rmse,          2),
    }
    fold_results.append(result)

    print(f"  Storm Accuracy : {result['storm_acc']}%")
    print(f"  Storm F1 Score : {result['storm_f1']}")
    print(f"  Solar drop MAE : {result['solar_mae']}%")
    print(f"  Wind  drop MAE : {result['wind_mae']}%")

    # Memory clear karo — naya fold ke liye
    tf.keras.backend.clear_session()

# ─── FINAL SUMMARY ───────────────────────────────────────
print("\n" + "=" * 55)
print("   CROSS VALIDATION FINAL RESULTS")
print("=" * 55)

results_df = pd.DataFrame(fold_results)

metrics = {
    "Storm Accuracy (%)": "storm_acc",
    "Storm F1 Score"    : "storm_f1",
    "Solar MAE (%)"     : "solar_mae",
    "Solar RMSE (%)"    : "solar_rmse",
    "Wind MAE (%)"      : "wind_mae",
    "Wind RMSE (%)"     : "wind_rmse",
}

for label, col in metrics.items():
    vals = results_df[col]
    print(f"  {label:<22}: "
          f"Mean={vals.mean():.2f}  "
          f"Std=±{vals.std():.2f}  "
          f"Min={vals.min():.2f}  "
          f"Max={vals.max():.2f}")

results_df.to_csv("cv_results.csv", index=False)
print("\n  Results saved → cv_results.csv")

# ─── CV RESULTS VISUALIZATION ────────────────────────────
fig, axes = plt.subplots(2, 3, figsize=(14, 8))
fig.suptitle('Walk-Forward Cross Validation Results',
             fontsize=14, fontweight='bold')

plot_data = [
    ("storm_acc",  "Storm Accuracy (%)",  axes[0,0], "#534AB7"),
    ("storm_f1",   "Storm F1 Score",      axes[0,1], "#534AB7"),
    ("solar_mae",  "Solar Drop MAE (%)",  axes[0,2], "#EF9F27"),
    ("solar_rmse", "Solar Drop RMSE (%)", axes[1,0], "#EF9F27"),
    ("wind_mae",   "Wind Drop MAE (%)",   axes[1,1], "#1D9E75"),
    ("wind_rmse",  "Wind Drop RMSE (%)",  axes[1,2], "#1D9E75"),
]

for col, title, ax, color in plot_data:
    vals  = results_df[col].values
    folds = results_df["fold"].values
    mean  = vals.mean()

    ax.bar(folds, vals, color=color, alpha=0.7, width=0.5)
    ax.axhline(mean, color=color, linestyle='--',
               linewidth=1.5, label=f'Mean={mean:.2f}')
    ax.fill_between([0.5, len(folds)+0.5],
                    mean - vals.std(),
                    mean + vals.std(),
                    alpha=0.15, color=color, label='±1 std')
    ax.set_title(title, fontsize=11)
    ax.set_xlabel('Fold')
    ax.set_xticks(folds)
    ax.legend(fontsize=9)
    ax.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig("cv_results_chart.png", dpi=150, bbox_inches='tight')
plt.show()
print("Chart saved → cv_results_chart.png")